version: 2

models:

  - name: patients_with_c1_test
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique
      - name: patient_birthdate
      - name: procedure_code
